# Generated by Django 5.2.4 on 2025-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
