# Generated by Django 5.2.4 on 2025-07-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfstore.topic'),
        ),
    ]
