# Generated by Django 5.2.4 on 2025-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0002_alter_parsedquestion_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_pdf', models.FileField(upload_to='pdfs/syllabus/')),
                ('past_questions_pdf', models.FileField(upload_to='pdfs/past_questions/')),
                ('notes_pdf', models.FileField(upload_to='pdfs/notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parsedquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='questionembedding',
            name='question',
        ),
        migrations.DeleteModel(
            name='NoteChunk',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='ParsedQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionEmbedding',
        ),
    ]
