# Generated by Django 5.2.4 on 2025-07-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0003_pdfupload_remove_parsedquestion_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('past_questions', 'Past Questions')], max_length=50)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
