# Generated by Django 5.2.4 on 2025-07-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0005_parsedquestion_topic_delete_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedquestion',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='parsedquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pdfstore.topic'),
        ),
    ]
