# Generated by Django 5.2.4 on 2025-07-18 10:58

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0006_parsedquestion_source_pdfupload_total_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('chapter', models.CharField(max_length=255)),
                ('hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=255)),
                ('subtopic', models.TextField()),
                ('hours', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='session',
        ),
        migrations.DeleteModel(
            name='ParsedQuestion',
        ),
        migrations.DeleteModel(
            name='PDFUpload',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
