# Generated by Django 5.2.4 on 2025-07-18 11:29

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0007_notecontent_pastquestion_syllabustopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_pdf', models.FileField(upload_to='uploads/syllabus/')),
                ('past_questions_pdf', models.FileField(upload_to='uploads/past_questions/')),
                ('notes_pdf', models.FileField(upload_to='uploads/notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NoteContent',
        ),
        migrations.DeleteModel(
            name='PastQuestion',
        ),
        migrations.DeleteModel(
            name='SyllabusTopic',
        ),
    ]
