# Generated by Django 5.2.4 on 2025-07-18 15:16

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0008_documentchunk_pdfupload_delete_notecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(help_text='The extracted content from the notes PDF for this subtopic.')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=4096, help_text='Vector embedding of the note content.')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The cleaned text of the question (without numbers/symbols).')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=4096, help_text='Vector embedding of the question text.')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(help_text='Name of the chapter/topic from the syllabus.', max_length=255, unique=True)),
                ('subtopic_content', models.TextField(help_text='Detailed content or description of the subtopics within this chapter.')),
                ('hours', models.FloatField(help_text='Allocated hours for this topic, used for question generation/weightage.')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        migrations.DeleteModel(
            name='PDFUpload',
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='topic',
            field=models.ForeignKey(help_text='The syllabus topic this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='pdfstore.syllabustopic'),
        ),
        migrations.AddField(
            model_name='notecontent',
            name='subtopic',
            field=models.ForeignKey(help_text='The syllabus topic/subtopic this note content is related to.', on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='pdfstore.syllabustopic'),
        ),
    ]
