# Generated by Django 5.2.4 on 2025-07-18 15:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0009_notecontent_pastquestion_syllabustopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustopic',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=4096, help_text='Vector embedding of subtopic content.', null=True),
        ),
    ]
