# Generated by Django 5.2.4 on 2025-07-18 16:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0010_syllabustopic_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabustopic',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embedding of subtopic content.', null=True),
        ),
    ]
