# Generated by Django 5.2.4 on 2025-07-19 03:16

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0011_alter_syllabustopic_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='topic',
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the question text (mpnet-base-v2).'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='question_text',
            field=models.TextField(help_text='The cleaned text of the past question (chunked if needed).'),
        ),
        migrations.DeleteModel(
            name='NoteContent',
        ),
        migrations.DeleteModel(
            name='SyllabusTopic',
        ),
    ]
