# Generated by Django 5.2.4 on 2025-07-20 12:16

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0012_remove_pastquestion_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255, unique=True)),
                ('subtopic_content', models.TextField()),
                ('hours', models.FloatField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the question text (mpnet-base-v2).')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='pdfstore.syllabustopic')),
            ],
        ),
    ]
