# Generated by Django 5.2.4 on 2025-07-20 13:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstore', '0014_alter_notecontent_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the note for answer checking'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the question text .'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
